var Players = [
  {
    nombre: "Lionel Messi",
    posicion: "forward",
    rol: "rw",
    foto: "/players/Forwards/messi.png",
    id: 0,
    lineup: false,
  },
  {
    nombre: "Sterling",
    posicion: "forward",
    rol: "rw",
    foto: "/players/Forwards/sterling.png",
    id: 1,
    lineup: false,
  },
  {
    nombre: "Cristiano Ronaldo",
    posicion: "forward",
    rol: "st",
    foto: "/players/Forwards/cristiano.png",
    id: 2,
    lineup: false,
  },
  {
    nombre: "Ronaldo",
    posicion: "forward",
    rol: "st",
    foto: "/players/Forwards/ronaldo.png",
    id: 3,
    lineup: false,
  },
  {
    nombre: "Neymar Jr",
    posicion: "forward",
    rol: "lw",
    foto: "/players/Forwards/neymar.png",
    id: 4,
    lineup: false,
  },
  {
    nombre: "Ronaldinho",
    posicion: "forward",
    rol: "lw",
    foto: "/players/Forwards/ronaldinho.png",
    id: 5,
    lineup: false,
  },

  {
    nombre: "De Bruyne",
    posicion: "midfielder",
    rol: "rcm",
    foto: "/players/Midfielders/de-bruyne.png",
    id: 6,
    lineup: false,
  },
  {
    nombre: "Gullit",
    posicion: "midfielder",
    rol: "rcm",
    foto: "/players/Midfielders/gullit.png",
    id: 7,
    lineup: false,
  },
  {
    nombre: "Patrick Vieira",
    posicion: "midfielder",
    rol: "cm",
    foto: "/players/Midfielders/vieira.png",
    id: 8,
    lineup: false,
  },
  {
    nombre: "Lothar Matthaus",
    posicion: "midfielder",
    rol: "cm",
    foto: "/players/Midfielders/matthaus.png",
    id: 9,
    lineup: false,
  },
  {
    nombre: "Luka Modric",
    posicion: "midfielder",
    rol: "lcm",
    foto: "/players/Midfielders/modric.png",
    id: 10,
    lineup: false,
  },
  {
    nombre: "Zinedine Zidane",
    posicion: "midfielder",
    rol: "lcm",
    foto: "/players/Midfielders/zidane.png",
    id: 11,
    lineup: false,
  },
  {
    nombre: "Toni Kroos",
    posicion: "midfielder",
    rol: "cm",
    foto: "/players/Midfielders/kroos.png",
    id: 12,
    lineup: false,
  },
  {
    nombre: "Marcelo",
    posicion: "defense",
    rol: "lb",
    foto: "/players/Defense/marcelo.png",
    id: 13,
    lineup: false,
  },
  {
    nombre: "Roberto Carlos",
    posicion: "defense",
    rol: "lb",
    foto: "/players/Defense/carlos.png",
    id: 14,
    lineup: false,
  },
  {
    nombre: "Maldini",
    posicion: "defense",
    rol: "rcb",
    foto: "/players/Defense/maldini.png",
    id: 15,
    lineup: false,
  },
  {
    nombre: "van Dijk",
    posicion: "defense",
    rol: "rcb",
    foto: "/players/Defense/van-dijk.png",
    id: 16,
    lineup: false,
  },
  {
    nombre: "Piqué",
    posicion: "defense",
    rol: "lcb",
    foto: "/players/Defense/pique.png",
    id: 17,
    lineup: false,
  },
  {
    nombre: "Sergio Ramos",
    posicion: "defense",
    rol: "lcb",
    foto: "/players/Defense/ramos.png",
    id: 18,
    lineup: false,
  },
  {
    nombre: "Carlos Alberto",
    posicion: "defense",
    rol: "rb",
    foto: "/players/Defense/alberto.png",
    id: 19,
    lineup: false,
  },
  {
    nombre: "Joshua Kimmich",
    posicion: "defense",
    rol: "rb",
    foto: "/players/Defense/kimmich.png",
    id: 20,
    lineup: false,
  },
  {
    nombre: "Ter Stegen",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/ter-stegen.png",
    id: 21,
    lineup: false,
  },
  {
    nombre: "van der Sar",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/van-der-sar.png",
    id: 22,
    lineup: false,
  },
  {
    nombre: "Alisson Becker",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/alisson.png",
    id: 23,
    lineup: false,
  },
  {
    nombre: "David De Gea",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/de-gea.png",
    id: 24,
    lineup: false,
  },
  {
    nombre: "Lev Yashin",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/yashin.png",
    id: 25,
    lineup: false,
  },
  {
    nombre: "Oblak",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/oblak.png",
    id: 26,
    lineup: false,
  },
  {
    nombre: "Andres Iniesta",
    posicion: "midfielder",
    rol: "lcm",
    foto: "/players/Midfielders/iniesta.png",
    id: 27,
    lineup: false,
  },
  {
    nombre: "Kylian Mbappe",
    posicion: "forward",
    rol: "rw",
    foto: "/players/Forwards/mbappe.png",
    id: 28,
    lineup: false,
  },
  {
    nombre: "Eden Hazard",
    posicion: "forward",
    rol: "lw",
    foto: "/players/Forwards/hazard.png",
    id: 29,
    lineup: false,
  },
  {
    nombre: "Mohammed Salah",
    posicion: "forward",
    rol: "rw",
    foto: "/players/Forwards/salah.png",
    id: 30,
    lineup: false,
  },
  {
    nombre: "Sadio Mane",
    posicion: "forward",
    rol: "lw",
    foto: "/players/Forwards/mane.png",
    id: 31,
    lineup: false,
  },
  {
    nombre: "Robert Lewandowski",
    posicion: "forward",
    rol: "st",
    foto: "/players/Forwards/lewandowski.png",
    id: 32,
    lineup: false,
  },
  {
    nombre: "Luis Suarez",
    posicion: "forward",
    rol: "st",
    foto: "/players/Forwards/suarez.png",
    id: 33,
    lineup: false,
  },
  {
    nombre: "Sergio Busquets",
    posicion: "midfielder",
    rol: "cm",
    foto: "/players/Midfielders/busquets.png",
    id: 34,
    lineup: false,
  },
  {
    nombre: "Frenkie De Jong",
    posicion: "midfielder",
    rol: "rcm",
    foto: "/players/Midfielders/de-jong.png",
    id: 35,
    lineup: false,
  },
  {
    nombre: "Andrea Pirlo",
    posicion: "midfielder",
    rol: "lcm",
    foto: "/players/Midfielders/pirlo.png",
    id: 36,
    lineup: false,
  },
  {
    nombre: "Paul Pogba",
    posicion: "midfielder",
    rol: "rcm",
    foto: "/players/Midfielders/pogba.png",
    id: 37,
    lineup: false,
  },
  {
    nombre: "Jordi Alba",
    posicion: "defense",
    rol: "lb",
    foto: "/players/Defense/jordi-alba.png",
    id: 38,
    lineup: false,
  },
  {
    nombre: "Andrew Robertson",
    posicion: "defense",
    rol: "lb",
    foto: "/players/Defense/robertson.png",
    id: 39,
    lineup: false,
  },
  {
    nombre: "Carles Puyol",
    posicion: "defense",
    rol: "rcb",
    foto: "/players/Defense/puyol.png",
    id: 40,
    lineup: false,
  },
  {
    nombre: "Franco Baresi",
    posicion: "defense",
    rol: "lcb",
    foto: "/players/Defense/baresi.png",
    id: 41,
    lineup: false,
  },
  {
    nombre: "Trent Alexander-Arnold",
    posicion: "defense",
    rol: "rb",
    foto: "/players/Defense/alexander-arnold.png",
    id: 42,
    lineup: false,
  },
  {
    nombre: "Dani Alves",
    posicion: "defense",
    rol: "rb",
    foto: "/players/Defense/dani-alves.png",
    id: 43,
    lineup: false,
  },
  {
    nombre: "Nesta",
    posicion: "defense",
    rol: "lcb",
    foto: "/players/Defense/nesta.png",
    id: 44,
    lineup: false,
  },
  {
    nombre: "Hummels",
    posicion: "defense",
    rol: "rcb",
    foto: "/players/Defense/hummels.png",
    id: 45,
    lineup: false,
  },
  {
    nombre: "Handanovic",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Goalkeepers/handanovic.png",
    id: 46,
    lineup: false,
  },
  {
    nombre: "void",
    posicion: "forward",
    rol: "lw",
    foto: "/players/Field/card.png",
    id: 47,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "forward",
    rol: "st",
    foto: "/players/Field/card.png",
    id: 48,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "forward",
    rol: "rw",
    foto: "/players/Field/card.png",
    id: 49,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "midfielder",
    rol: "lcm",
    foto: "/players/Field/card.png",
    id: 50,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "midfielder",
    rol: "cm",
    foto: "/players/Field/card.png",
    id: 51,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "midfielder",
    rol: "rcm",
    foto: "/players/Field/card.png",
    id: 52,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "defense",
    rol: "lb",
    foto: "/players/Field/card.png",
    id: 53,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "defense",
    rol: "lcb",
    foto: "/players/Field/card.png",
    id: 54,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "defense",
    rol: "rcb",
    foto: "/players/Field/card.png",
    id: 55,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "defense",
    rol: "rb",
    foto: "/players/Field/card.png",
    id: 56,
    lineup: true,
  },
  {
    nombre: "void",
    posicion: "goalkeeper",
    rol: "gk",
    foto: "/players/Field/card.png",
    id: 57,
    lineup: true,
  },
];

export default Players;
